name: "Test document-summary-list-csv-creater"
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: npm ci
      - run: npm run build
      - run: npm test
      - uses: ./
        with:
          dirPath: ./sampleFiles
        id: create_csv
      - uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: ./sampleFiles/summary.csv
          FILE_DATA: ${{ steps.create_csv.outputs.csv }}
      - run: cat ./sampleFiles/summary.csv
